POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "email": "tkjkj.alstig@gmail.com",
    "password": "Ansmark45"
}

###

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "therese.alstig@gmail.com",
    "password": "Ansmark45"
}

###
POST http://localhost:3001/api/auth/logout

###
GET  http://localhost:3001/api/auth/authorised